# See claude code environment variables documents at https://code.claude.com/docs/en/settings
[env]

[tools]
claude = "latest"
python = "3.12"
ruff = "latest"
uv = "latest"

# === Tasks
[tasks.venv-create]
description = "✨ Create Python virtual environment (.venv)"
run = "uv venv"

[tasks.venv-remove]
description = "💥 Remove Python virtual environment folder (.venv)"
run = "rm -r .venv"

[tasks.inst]
description = "💾 Install Python dependencies (dev, test, doc, etc.) via uv"
run = "uv sync --all-extras"

[tasks.export]
description = "💾 Expore Core Python dependencies to requirements.txt via uv"
run = "uv export --format requirements-txt --no-dev --no-emit-project > requirements.txt"

[tasks.test]
description = "🧪 Run tests with pytest"
run = ".venv/bin/pytest tests"
