
[project]
name = "learn_personal_portfolio_ai"
version = "0.1.1"
requires-python = ">=3.12,<4.0"

# Core Dependencies
dependencies = [
]

[project.optional-dependencies]

# (Unit/Coverage/Integration/Load) Test dependenceies
test = [
    "pytest>=8.2.2,<9.0.0", # Testing framework
]

[tool.setuptools.packages.find]
where = ["."]
include = ["learn_personal_portfolio_ai*"]
exclude = [
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
